---
title: "Exercise 1"
---

Create your first `teal` application!

- read [`teal::init()`](https://insightsengineering.github.io/teal/latest-tag/reference/init.html) documentation
- use [`random.cdisc.data::radsl(cached = TRUE)`](https://insightsengineering.github.io/random.cdisc.data/main/reference/radsl.html) to create a dummy ADSL dataset
- use [`teal::example_module()`](https://insightsengineering.github.io/teal/latest-tag/reference/example_module.html) to create a dummy module

### Code

```{r ex, message = FALSE}
library(random.cdisc.data)
library(teal)

data <- teal_data()
data <- within(data, {
  ADSL <- radsl(cached = TRUE)
})
# set datanames
datanames <- c("ADSL")
datanames(data) <- datanames

## Reusable Configuration For Modules
ADSL <- data[["ADSL"]]

header <- tags$span(
  style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
  tags$span("Excercise 1", style = "font-size: 30px;"),
)

footer <- tags$p(
  "This teal app is brought to you by PhUSE SDE Basel."
)

app <- init(
  data = data,
  modules = modules(
    example_module()
  ),
  title = build_app_title("Basic Teal Demo App"),
  header = header,
  footer = footer
)

if (Sys.getenv("QUARTO_ROOT") == "") {
  shinyApp(app$ui, app$server)
}
```

### URL

```{r shinylive_url, echo = FALSE, results = 'asis'}
code <- paste0(knitr::knit_code$get("ex"), collapse = "\n")
url <- roxy.shinylive::create_shinylive_url(code)
cat(sprintf("[Open in Shinylive](%s)\n\n", url))
```

### App

```{r shinylive_iframe, echo = FALSE, out.width = '150%'}
knitr::include_url(url, height = "800px")
```
